version: '3'

name: keycloak

volumes:
  keycloak-data:

services:
  keycloak-postgres:
    image: postgres:15.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - keycloak-data:/var/lib/postgresql/data
      - ./init/keycloak/data:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
        ]
      interval: 5s
      timeout: 5s
      retries: 10
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: $POSTGRES_USER
      KC_DB_PASSWORD: $POSTGRES_PASSWORD
      DB_SCHEMA: $POSTGRES_DB_SCHEMA
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: $KEYCLOAK_ADMIN
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
    volumes:
      - ./init/keycloak/realms:/opt/keycloak/data/import:ro
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    command:
      - start-dev --import-realm
